version: '3.7'

services:
  dfe-manager-kafka:
    image: repo.ms.gov.br/sgi/devops/kafka-manager:1.3.3.22-alpine3.9
    networks:
      - kafka_net
      - proxy_net
    environment:
      ZK_HOSTS: "dfe-zk1:2181,dfe-zk2:2181,dfe-zk3:2181,dfe-zk4:2181,dfe-zk5:2181"
      HTTP_CONTEXT: "/dfe/manager/kafka"
    deploy:
      placement:
        constraints:
          - node.labels.region == sup
      replicas: 1
      update_config:
        parallelism: 1
        delay: 80s
      labels:
        - "traefik.frontend.entryPoints=http"
        - "traefik.port=9000"
        - "traefik.backend=dfe-manager-kafka"
        - "traefik.frontend.rule=Host: api.sgi.ms.gov.br;PathPrefix:/dfe/manager/kafka"
        - "traefik.docker.network=proxy_net"
      resources:
        limits:
          memory: 512M
networks:
  kafka_net:
    external: true
  proxy_net:
    external: true
 
