version: '3.7'

services:

  ignite-0:
    image: icorrea/apache-ignite:2.6.0-alpine
    networks:
      - ignite-net
    # Exposing ports for inter cluster communication
    expose:
      - 11211   
      - 47100
      - 47500
      - 49112
      - 10800
    ports:
      - "10800:10800"
    volumes:
      - ~/srv/ignite/n0-data:/opt/apache-ignite/work/db

  ignite-1:
    image: icorrea/apache-ignite:2.6.0-alpine
    depends_on:
      - ignite-0
    networks:
      - ignite-net
    # Exposing ports for inter cluster communication
    expose:
      - 11211   
      - 47100
      - 47500
      - 49112
      - 10800
    ports:
      - "10801:10800"
    volumes:
      - ~/srv/ignite/n1-data:/opt/apache-ignite/work/db

  ignite-2:
    image: icorrea/apache-ignite:2.6.0-alpine
    depends_on:
      - ignite-0
      - ignite-1
    networks:
      - ignite-net
    # Exposing ports for inter cluster communication
    expose:
      - 11211   
      - 47100
      - 47500
      - 49112
      - 10800
    ports:
      - "10802:10800"
    volumes:
      - ~/srv/ignite/n2-data:/opt/apache-ignite/work/db

networks:
  ignite-net:
    external: true

