version: "3"

services:

  knowage:
    image: knowagelabs/knowage-server-docker:develop
    environment:
      - DB_ENV_MYSQL_USER=knowageuser
      - DB_ENV_MYSQL_DATABASE=knowagedb
      - DB_ENV_MYSQL_PASSWORD=senha123
      - DB_PORT_3306_TCP_ADDR=knowagedb
      - DB_PORT_3306_TCP_PORT=3306
    networks:
        - spark_net
    ports:
        - "8090:8080"
    environment:
        - WAIT_MYSQL=true

  knowagedb:
    image: mysql:5.6
    hostname: knowagedb
    networks:
        - spark_net
    environment:
        - MYSQL_USER=knowageuser
        - MYSQL_PASSWORD=senha123
        - MYSQL_DATABASE=knowagedb
        - MYSQL_ROOT_PASSWORD=senha123
    volumes:
      - ~/svr/knowagedb/mysql:/var/lib/mysql

networks:
  spark_net:
    external: true

