version: "3.5"

services:

  d0090-nifi-registry:
    image: icorrea/nifi-registry:0.5.0-alpine3.10
    hostname: d0090-nifi-registry
    environment:
      - AUTH=tls
      - KEYSTORE_PATH=/opt/certs/keystore.jks
      - KEYSTORE_TYPE=JKS
      - KEYSTORE_PASSWORD=5CdN6VLOOiwHtuyMAKQde4V1HfzwD+2iCsrRlkb9CUI
      - TRUSTSTORE_PATH=/opt/certs/truststore.jks
      - TRUSTSTORE_PASSWORD=bQyXj7p0LgwbqyIiB0AG7gOu+ZsUv+CQgu7fEkZxBeM
      - TRUSTSTORE_TYPE=JKS
      - INITIAL_ADMIN_IDENTITY=CN=sys_admin, OU=NIFI
    ports:
      - 18443:18443
    networks:
      - cotin_dados_net
    volumes:
      - ~/srv/dfe/nifi-registry/database:/opt/nifi-registry/database
      - ~/srv/dfe/nifi-registry/flow_storage:/opt/nifi-registry/flow_storage
      - ~/srv/dfe/nifi-registry/tls/certs/d0090-nifi-registry:/opt/certs

  d0090-prd-nifi:
    image: icorrea/nifi:1.9.2-alpine3.10
    hostname: d0090-prd-nifi
    networks:
      - cotin_dados_net
    depends_on:
      - d0090-nifi-registry
    ports:
      - 8443:8443 # secured HTTPs Web Port
    environment:
      - NIFI_WEB_PROXY_CONTEXT_PATH=/prd/nifi
      - NIFI_WEB_PROXY_HOST=d0090-prd-nifi
      - NIFI_WEB_HTTPS_HOST=d0090-prd-nifi
      - NIFI_WEB_HTTPS_PORT=8443
      - AUTH=tls
      - KEYSTORE_PATH=/opt/certs/keystore.jks
      - KEYSTORE_TYPE=JKS
      - KEYSTORE_PASSWORD=Ulrm8iSUhUBu+yZy+4972hh2M9+b8KSEs9pt1ECOXsE
      - TRUSTSTORE_PATH=/opt/certs/truststore.jks
      - TRUSTSTORE_PASSWORD=a6xNdeYQlVA3cX0sAjsBe4xLQ/5UIneMQAuYhwXm+ys
      - TRUSTSTORE_TYPE=JKS
      - INITIAL_ADMIN_IDENTITY=CN=sys_admin, OU=NIFI
    volumes:
      - ~/srv/dfe/dev/d0090-prd-nifi/state:/opt/nifi/state
      - ~/srv/dfe/dev/d0090-prd-nifi/database_repository:/opt/nifi/database_repository
      - ~/srv/dfe/dev/d0090-prd-nifi/flowfile_repository:/opt/nifi/flowfile_repository
      - ~/srv/dfe/dev/d0090-prd-nifi/content_repository:/opt/nifi/content_repository
      - ~/srv/dfe/dev/d0090-prd-nifi/provenance_repository:/opt/nifi/provenance_repository
      - ~/srv/dfe/nifi/tls/certs/d0090-prd-nifi:/opt/certs

networks:
  cotin_dados_net:
    external: true

