version: "3"

services:

  cassandra-1:
    image: icorrea/cassandra:3.11-debian
    networks:
      - cassandra-net
    environment:
      - CASSANDRA_CLUSTER_NAME= cluster_1
      - CASSANDRA_SEEDS=cassandra-1,cassandra-2
      - CASSANDRA_START_RPC=true
      - CASSANDRA_RPC_ADDRESS="0.0.0.0"
      - CASSANDRA_BROADCAST_ADDRESS=cassandra-1
      - CASSANDRA_LISTEN_ADDRESS=cassandra-1
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=200M
    volumes:
      - ~/srv/cassandra/data1:/usr/local/apache-cassandra-3.11.4

  cassandra-2:
    image: icorrea/cassandra:3.11-debian
    networks:
      - cassandra-net
    environment:
      - CASSANDRA_CLUSTER_NAME= cluster_1
      - CASSANDRA_SEEDS=cassandra-1,cassandra-2
      - CASSANDRA_START_RPC=true
      - CASSANDRA_RPC_ADDRESS="0.0.0.0"
      - CASSANDRA_BROADCAST_ADDRESS=cassandra-2
      - CASSANDRA_LISTEN_ADDRESS=cassandra-2
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=200M
    volumes:
      - ~/srv/cassandra/data2:/usr/local/apache-cassandra-3.11.4
    depends_on:
      - cassandra-1

 
networks:
  cassandra-net:
    external: true

