version: '3.5'

services:

  master:
    image: icorrea/spark:2.3.2-debian-jessie
    command: bin/spark-class org.apache.spark.deploy.master.Master -h master
    networks:
      - spark_cfmt_net
      - consul_net
    deploy:
      placement:
        constraints:
          - node.labels.region == sup
      replicas: 1
      update_config:
        parallelism: 1
        delay: 80s
      labels:
        - "traefik.frontend.entryPoints=http"
        - "traefik.port=8080"
        - "traefik.backend=cfmt-spark"
        - "traefik.frontend.rule=Host:api.sgi.ms.gov.br;PathPrefixStrip:/cfmt/spark"
        - "traefik.docker.network=consul_net"
      resources:
        limits:
          memory: 1g
    environment:
      MASTER: spark://master:7077
      SPARK_CONF_DIR: /conf
    expose:
      - 6066:6066
      - 7077:7077

  worker:
    image: icorrea/spark:2.3.2-debian-jessie
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
    networks:
      - spark_cfmt_net
    environment:
      SPARK_CONF_DIR: /conf
      SPARK_WORKER_CORES: 1
      SPARK_WORKER_MEMORY: 1g
    deploy:
      placement:
        constraints:
          - node.labels.region == sup
      replicas: 2
      update_config:
        parallelism: 1
        delay: 80s
      resources:
        limits:
          memory: 1g
    depends_on:
      - master

  zeppelin:
    image: icorrea/zeppelin:0.8.0-ubuntu
    networks:
      - spark_cfmt_net
      - consul_net
    deploy:
      placement:
        constraints:
          - node.labels.region == sup
      replicas: 1
      update_config:
        parallelism: 1
        delay: 80s
      labels:
        - "traefik.frontend.entryPoints=http"
        - "traefik.port=8080"
        - "traefik.backend=cfmt-zeppelin"
        - "traefik.frontend.rule=Host:api.sgi.ms.gov.br;PathPrefixStrip:/cfmt/zeppelin"
        - "traefik.docker.network=consul_net"
      resources:
        limits:
          memory: 1g
    volumes:
      - /swarm/cfmt/zeppelin-note:/zeppelin/notebook

networks:
  spark_cfmt_net:
    external: true
