version: '3'

services:

  postgres:
    image: icorrea/postgresql:11-alpine3.8
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: icorrea/redis:5.0.0-alpine3.8
    restart: unless-stopped

  superset:
    image: icorrea/superset:0.28.1-alpine3.8
    depends_on:
      - postgres
      - redis
    volumes:
      - ./superset_config.py:/etc/superset/superset_config.py
    ports:
      - "127.0.0.1:8088:8088"

volumes:
  postgres:
    external: false
  redis:
    external: false
