version: '3'

services:
  zookeeper:
    image: icorrea/zookeeper:0.10-centos7
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888
    networks:
      - dfe_net

  kafka:
    image: icorrea/kafka:0.10-centos7
    ports:
     - 9092:9092
    networks:
      - dfe_net
    depends_on:
     - zookeeper
    environment:
     - ZOOKEEPER_CONNECT=zookeeper:2181

  sqlserver:
    image: microsoft/mssql-server-linux:latest
    ports:
     - 1433:1433
    environment:
     - ACCEPT_EULA=Y
     - MSSQL_PID=Standard
     - SA_PASSWORD=Senha123
     - MSSQL_AGENT_ENABLED=true

  connect:
    image: icorrea/connect:0.10-centos7
    ports:
     - 8083:8083
    networks:
      - dfe_net
    depends_on:
     - kafka
     - sqlserver
    environment:
     - BOOTSTRAP_SERVERS=kafka:9092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=my_connect_configs
     - OFFSET_STORAGE_TOPIC=my_connect_offsets
     - STATUS_STORAGE_TOPIC=my_connect_statuses

networks:
  - dfe_net:
      external: true
