version: '3'

services:

  zookeeper:
    image: debezium/zookeeper:0.10-centos7
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
    networks:
      - dfe_net

  kafka:
    image: debezium/kafka:0.10-centos7
    ports:
      - 9092:9092
    networks:
      - dfe_net
    depends_on:
      - zookeeper
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181

  postgres:
    image: debezium/example-postgres:0.10-centos7
    ports:
      - 5432:5432
    networks:
      - dfe_net
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  connect:
    image: debezium/connect:0.10-centos7
    ports:
      - 8083:8083
    networks:
      - dfe_net
    depends_on:
      - kafka
      - postgres
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses

networks:
  - dfe_net:
      external: true

