version: '3'

services:

  redis:
    image: redis:3.2
    restart: always
    ports:
      - 6379:6379
    networks:
      - spark_net
    volumes:
      - ~/svr/superset/redis:/data

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_USER: superset
      MYSQL_PASSWORD: superset
      MYSQL_DATABASE: superset
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    networks:
      - spark_net
    volumes:
      - ~/svr/superset/mysql:/var/lib/mysql

  superset:
    image: icorrea/apache-superset:0.33-python3.6
    restart: always
    environment:
      MYSQL_USER: superset
      MYSQL_PASS: superset
      MYSQL_DATABASE: superset
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      REDIS_HOST: redis
      REDIS_PORT: 6379
#      SUPERSET_ENV: prod
#      GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS}
    ports:
      - 8088:8088
      - 5555:5555
    networks:
      - spark_net
    depends_on:
      - mysql
      - redis
    volumes:
      - ~/svr/superset/config/:/home/superset/config/

networks:
  spark_net:
    external: true

