version: '3'

services:

  sefa-redis:
    image: redis:3.2
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ~/srv/sefa-superset/redis:/data

  sefa-postgres:
    image: postgres:10
    restart: always
    environment:
      POSTGRES_DB: superset
      POSTGRES_PASSWORD: superset
      POSTGRES_USER: superset
    ports:
      - 5432:5432
    volumes:
      - ~/srv/sefa-superset/postgresql:/var/lib/postgresql/data

  sefa-superset:
    image: icorrea/apache-superset:0.27.0-debian
    restart: always
    environment:
      POSTGRES_DB: superset
      POSTGRES_USER: superset
      POSTGRES_PASSWORD: superset
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      REDIS_HOST: sefa-redis
      REDIS_PORT: 6379
      SUPERSET_ENV: local
    ports:
      - 8088:8088
    command: "tail -f /dev/null"
    depends_on:
      - sefa-postgres
      - sefa-redis
    ports:
      - "8088:8088"
    volumes:
      - ~/srv/sefa-superset:/home/work/incubator-superset
      - ~/srv/sefa-superset/modules:/home/work/incubator-superset/superset/assets/node_modules

